In [5]:
# Ma trận A và B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Phép nhân ma trận
C = np.dot(A, B)
print(C)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
